### ISSUE TITLE
Right click Save to Pinboard not working

### ISSUE THREAD

**Issue by tekumara** [yasuyk/Pinboard-Chrome-Extension#3]
When right clicking on a URL or selected text, and clicking Save to Pinboard, nothing happens.

**Comment by yasuyk** [comment]
Hi @tukushan, Thank you for the bug report.
I will fix the bug this weekend.

**Comment by yasuyk** [comment]
The problem occurs certainly on the chrome webstore version 0.0.10, but that doesn't occur on the [same version](https://github.com/yasuyk/Pinboard-Chrome-Extension/releases/tag/0.0.10) in development mode.

Hmmm...
I released version 0.0.11 on which some unrelated thing fixed, then The problem doesn't occur on the new chrome webstore version. So, I close this issue.

@tukushan, Please try new chrome webstore version 0.0.11. If the problem occurs on new version, reopen this issue and tell me.

**Comment by yasuyk** [comment]
Sorry, the problem occurs on the version 0.0.11.
